version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" 
      - "15672:15672" 
    environment:
      RABBITMQ_ERLANG_COOKIE: 'sua_secret_erlang'
      RABBITMQ_DEFAULT_USER: 'root'
      RABBITMQ_DEFAULT_PASS: 'root'
    volumes:
      - ./data:/var/lib/rabbitmq
    restart: unless-stopped
